DEBUG 2019-01-31 01:39:10,938: 	 Executing command: 'submit'
DEBUG 2019-01-31 01:39:10,938: 	 Found CRAB cache file /afs/cern.ch/user/k/knash/.crab3
DEBUG 2019-01-31 01:39:10,952: 	 Checking credentials
DEBUG 2019-01-31 01:39:10,953: 	 Found proxy file /tmp/x509up_u16529
DEBUG 2019-01-31 01:39:10,953: 	 Getting proxy life time left
DEBUG 2019-01-31 01:39:12,063: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u16529 -timeleft
 output : 42167

 error: 
 retcode : 0
DEBUG 2019-01-31 01:39:13,073: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u16529 -actimeleft
 output : 42167

 error: 
 retcode : 0
DEBUG 2019-01-31 01:39:13,074: 	 Proxy valid for 11:42:47 hours
INFO 2019-01-31 01:39:13,074: 	 Will use CRAB configuration file crab3_TEMP.py
DEBUG 2019-01-31 01:39:13,074: 	 Loading CRAB configuration file.
ERROR 2019-01-31 01:39:13,082: 	 The 'dryrun' option is not compatible with the 'Automatic' splitting mode (default).
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2019-01-31 01:39:13,082: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 303, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 89, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: The 'dryrun' option is not compatible with the 'Automatic' splitting mode (default).
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2019-01-31 01:40:15,292: 	 Executing command: 'status'
DEBUG 2019-01-31 01:40:15,292: 	 Found CRAB cache file /afs/cern.ch/user/k/knash/.crab3
ERROR 2019-01-31 01:40:15,293: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/k/knash/NanoAODskim/CMSSW_10_2_9/src/PhysicsTools/NanoHRT/test/crab_projects/crab_BstarToTW_private_M-2800_LH_TuneCP5_13TeV-madgraph-pythia8NanoSlimmed_v0
ERROR 2019-01-31 01:40:15,294: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 39, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 262, in __init__
    self.validateOptions()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 1022, in validateOptions
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 580, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 441, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/k/knash/NanoAODskim/CMSSW_10_2_9/src/PhysicsTools/NanoHRT/test/crab_projects/crab_BstarToTW_private_M-2800_LH_TuneCP5_13TeV-madgraph-pythia8NanoSlimmed_v0
DEBUG 2019-01-31 01:53:21,127: 	 Executing command: 'submit'
DEBUG 2019-01-31 01:53:21,128: 	 Found CRAB cache file /afs/cern.ch/user/k/knash/.crab3
DEBUG 2019-01-31 01:53:21,141: 	 Checking credentials
DEBUG 2019-01-31 01:53:21,141: 	 Found proxy file /tmp/x509up_u16529
DEBUG 2019-01-31 01:53:21,141: 	 Getting proxy life time left
DEBUG 2019-01-31 01:53:22,149: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u16529 -timeleft
 output : 43122

 error: 
 retcode : 0
DEBUG 2019-01-31 01:53:23,161: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u16529 -actimeleft
 output : 43121

 error: 
 retcode : 0
DEBUG 2019-01-31 01:53:23,161: 	 Proxy lifetime 43122 secs is different from voms extension lifetime 43121 secs for proxy: /tmp/x509up_u16529
DEBUG 2019-01-31 01:53:23,161: 	 Proxy valid for 11:58:41 hours
INFO 2019-01-31 01:53:23,161: 	 Will use CRAB configuration file crab3_TEMP.py
DEBUG 2019-01-31 01:53:23,162: 	 Loading CRAB configuration file.
DEBUG 2019-01-31 01:53:23,167: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-01-31 01:53:23,167: 	 Invalid CRAB configuration: A local DBS instance 'phys03' was specified for reading an input dataset of tier None.
Datasets of tier different than USER must be read from the global DBS instance; this is, set Data.inputDBS = 'global'.
If Data.inputDBS would not be specified, the default 'global' ('https://cmsweb.cern.ch/dbs/prod/global/DBSReader') would be used.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2019-01-31 01:53:23,168: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 303, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 89, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Invalid CRAB configuration: A local DBS instance 'phys03' was specified for reading an input dataset of tier None.
Datasets of tier different than USER must be read from the global DBS instance; this is, set Data.inputDBS = 'global'.
If Data.inputDBS would not be specified, the default 'global' ('https://cmsweb.cern.ch/dbs/prod/global/DBSReader') would be used.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2019-01-31 12:23:29,408: 	 Executing command: 'submit'
DEBUG 2019-01-31 12:23:29,409: 	 Found CRAB cache file /afs/cern.ch/user/k/knash/.crab3
DEBUG 2019-01-31 12:23:29,423: 	 Checking credentials
DEBUG 2019-01-31 12:23:29,423: 	 Found proxy file /tmp/x509up_u16529
DEBUG 2019-01-31 12:23:29,423: 	 Getting proxy life time left
DEBUG 2019-01-31 12:23:30,855: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u16529 -timeleft
 output : 41669

 error: 
 retcode : 0
DEBUG 2019-01-31 12:23:32,293: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u16529 -actimeleft
 output : 41666

 error: 
 retcode : 0
DEBUG 2019-01-31 12:23:32,293: 	 Proxy lifetime 41669 secs is different from voms extension lifetime 41666 secs for proxy: /tmp/x509up_u16529
DEBUG 2019-01-31 12:23:32,293: 	 Proxy valid for 11:34:26 hours
INFO 2019-01-31 12:23:32,293: 	 Will use CRAB configuration file crab3_TEMPBstarToTW_private_M-2800_LH_TuneCP5_13TeV-madgraph-pythia8.py
DEBUG 2019-01-31 12:23:32,294: 	 Loading CRAB configuration file.
DEBUG 2019-01-31 12:23:32,311: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-01-31 12:23:32,311: 	 Invalid CRAB configuration: A local DBS instance 'phys03' was specified for reading an input dataset of tier None.
Datasets of tier different than USER must be read from the global DBS instance; this is, set Data.inputDBS = 'global'.
If Data.inputDBS would not be specified, the default 'global' ('https://cmsweb.cern.ch/dbs/prod/global/DBSReader') would be used.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2019-01-31 12:23:32,311: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 303, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 89, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Invalid CRAB configuration: A local DBS instance 'phys03' was specified for reading an input dataset of tier None.
Datasets of tier different than USER must be read from the global DBS instance; this is, set Data.inputDBS = 'global'.
If Data.inputDBS would not be specified, the default 'global' ('https://cmsweb.cern.ch/dbs/prod/global/DBSReader') would be used.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2019-01-31 12:29:46,399: 	 Executing command: 'submit'
DEBUG 2019-01-31 12:29:46,400: 	 Found CRAB cache file /afs/cern.ch/user/k/knash/.crab3
DEBUG 2019-01-31 12:29:46,560: 	 Checking credentials
DEBUG 2019-01-31 12:29:46,565: 	 Found proxy file /tmp/x509up_u16529
DEBUG 2019-01-31 12:29:46,565: 	 Getting proxy life time left
DEBUG 2019-01-31 12:31:40,612: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u16529 -timeleft
 output : 41179

 error: 
 retcode : 0
DEBUG 2019-01-31 12:31:46,212: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u16529 -actimeleft
 output : 41172

 error: 
 retcode : 0
DEBUG 2019-01-31 12:31:46,225: 	 Proxy lifetime 41179 secs is different from voms extension lifetime 41172 secs for proxy: /tmp/x509up_u16529
DEBUG 2019-01-31 12:31:46,225: 	 Proxy valid for 11:26:12 hours
INFO 2019-01-31 12:31:46,230: 	 Will use CRAB configuration file crab3_TEMPBstarToTW_private_M-1200_LH_TuneCP5_13TeV-madgraph-pythia8.py
DEBUG 2019-01-31 12:31:46,236: 	 Loading CRAB configuration file.
DEBUG 2019-01-31 12:31:46,272: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-01-31 12:31:46,294: 	 Working area '/afs/cern.ch/work/k/knash/NanoAODskim/CMSSW_10_2_9/src/PhysicsTools/NanoHRT/test/crab_projects/crab_BstarToTW_private_M-1200_LH_TuneCP5_13TeV-madgraph-pythia8NanoSlimNtuples_v1' already exists 
Please change the requestName in the config file
ERROR 2019-01-31 12:31:46,295: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 307, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/k/knash/NanoAODskim/CMSSW_10_2_9/src/PhysicsTools/NanoHRT/test/crab_projects/crab_BstarToTW_private_M-1200_LH_TuneCP5_13TeV-madgraph-pythia8NanoSlimNtuples_v1' already exists 
Please change the requestName in the config file
DEBUG 2019-01-31 12:31:53,237: 	 Executing command: 'submit'
DEBUG 2019-01-31 12:31:53,239: 	 Found CRAB cache file /afs/cern.ch/user/k/knash/.crab3
DEBUG 2019-01-31 12:31:53,871: 	 Checking credentials
DEBUG 2019-01-31 12:31:53,913: 	 Found proxy file /tmp/x509up_u16529
DEBUG 2019-01-31 12:31:53,914: 	 Getting proxy life time left
DEBUG 2019-01-31 12:37:14,686: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u16529 -timeleft
 output : 40846

 error: 
 retcode : 0
DEBUG 2019-01-31 12:37:21,425: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u16529 -actimeleft
 output : 40837

 error: 
 retcode : 0
DEBUG 2019-01-31 12:37:21,426: 	 Proxy lifetime 40846 secs is different from voms extension lifetime 40837 secs for proxy: /tmp/x509up_u16529
DEBUG 2019-01-31 12:37:21,426: 	 Proxy valid for 11:20:37 hours
INFO 2019-01-31 12:37:21,430: 	 Will use CRAB configuration file crab3_TEMPBstarToTW_private_M-2000_LH_TuneCP5_13TeV-madgraph-pythia8.py
DEBUG 2019-01-31 12:37:21,431: 	 Loading CRAB configuration file.
DEBUG 2019-01-31 12:37:21,470: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-01-31 12:37:21,475: 	 Working area '/afs/cern.ch/work/k/knash/NanoAODskim/CMSSW_10_2_9/src/PhysicsTools/NanoHRT/test/crab_projects/crab_BstarToTW_private_M-2000_LH_TuneCP5_13TeV-madgraph-pythia8NanoSlimNtuples_v1' already exists 
Please change the requestName in the config file
ERROR 2019-01-31 12:37:21,475: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 307, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/k/knash/NanoAODskim/CMSSW_10_2_9/src/PhysicsTools/NanoHRT/test/crab_projects/crab_BstarToTW_private_M-2000_LH_TuneCP5_13TeV-madgraph-pythia8NanoSlimNtuples_v1' already exists 
Please change the requestName in the config file
DEBUG 2019-01-31 12:38:53,172: 	 Executing command: 'submit'
DEBUG 2019-01-31 12:38:53,172: 	 Found CRAB cache file /afs/cern.ch/user/k/knash/.crab3
DEBUG 2019-01-31 12:38:53,185: 	 Checking credentials
DEBUG 2019-01-31 12:38:53,185: 	 Found proxy file /tmp/x509up_u16529
DEBUG 2019-01-31 12:38:53,185: 	 Getting proxy life time left
DEBUG 2019-01-31 12:38:54,407: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u16529 -timeleft
 output : 40745

 error: 
 retcode : 0
DEBUG 2019-01-31 12:38:55,417: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u16529 -actimeleft
 output : 40743

 error: 
 retcode : 0
DEBUG 2019-01-31 12:38:55,417: 	 Proxy lifetime 40745 secs is different from voms extension lifetime 40743 secs for proxy: /tmp/x509up_u16529
DEBUG 2019-01-31 12:38:55,417: 	 Proxy valid for 11:19:03 hours
INFO 2019-01-31 12:38:55,418: 	 Will use CRAB configuration file crab3_TEMPWkkToRWToTri_Wkk3000R200_ZA_private_TuneCP5_13TeV-madgraph-pythia8_v2.py
DEBUG 2019-01-31 12:38:55,418: 	 Loading CRAB configuration file.
DEBUG 2019-01-31 12:38:55,442: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-01-31 12:38:55,443: 	 Working area '/afs/cern.ch/work/k/knash/NanoAODskim/CMSSW_10_2_9/src/PhysicsTools/NanoHRT/test/crab_projects/crab_WkkToRWToTri_Wkk3000R200_ZA_private_TuneCP5_13TeV-madgraph-pythia8_v2NanoSlimNtuples_v1' already exists 
Please change the requestName in the config file
ERROR 2019-01-31 12:38:55,443: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 307, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1812/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/k/knash/NanoAODskim/CMSSW_10_2_9/src/PhysicsTools/NanoHRT/test/crab_projects/crab_WkkToRWToTri_Wkk3000R200_ZA_private_TuneCP5_13TeV-madgraph-pythia8_v2NanoSlimNtuples_v1' already exists 
Please change the requestName in the config file
DEBUG 2019-02-01 00:56:17,431: 	 Executing command: 'submit'
DEBUG 2019-02-01 00:56:17,431: 	 Found CRAB cache file /afs/cern.ch/user/k/knash/.crab3
DEBUG 2019-02-01 00:56:17,443: 	 Checking credentials
DEBUG 2019-02-01 00:56:17,445: 	 Found proxy file /tmp/x509up_u16529
DEBUG 2019-02-01 00:56:17,445: 	 Getting proxy life time left
DEBUG 2019-02-01 00:56:20,083: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u16529 -timeleft
 output : 39679

 error: 
 retcode : 0
ERROR 2019-02-01 00:56:20,301: 	 Keyboard Interrupted
DEBUG 2019-03-06 17:10:53,283: 	 Executing command: 'submit'
DEBUG 2019-03-06 17:10:53,286: 	 Found CRAB cache file /afs/cern.ch/user/k/knash/.crab3
DEBUG 2019-03-06 17:10:53,349: 	 Checking credentials
DEBUG 2019-03-06 17:10:53,352: 	 Found proxy file /tmp/x509up_u16529
DEBUG 2019-03-06 17:10:53,352: 	 Getting proxy life time left
DEBUG 2019-03-06 17:10:56,005: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u16529 -timeleft
 output : 26009

 error: 
 retcode : 0
DEBUG 2019-03-06 17:10:58,771: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u16529 -actimeleft
 output : 26006

 error: 
 retcode : 0
DEBUG 2019-03-06 17:10:58,771: 	 Proxy lifetime 26009 secs is different from voms extension lifetime 26006 secs for proxy: /tmp/x509up_u16529
DEBUG 2019-03-06 17:10:58,771: 	 Proxy valid for 07:13:26 hours
INFO 2019-03-06 17:10:58,771: 	 Will use CRAB configuration file crab3_TEMPJetHT.py
DEBUG 2019-03-06 17:10:58,771: 	 Loading CRAB configuration file.
ERROR 2019-03-06 17:10:58,782: 	 Error while loading CRAB configuration:
EOL while scanning string literal (crab3_TEMPJetHT.py, line 31)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2019-03-06 17:10:58,782: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 309, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 87, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
EOL while scanning string literal (crab3_TEMPJetHT.py, line 31)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2019-03-06 17:15:06,491: 	 Executing command: 'submit'
DEBUG 2019-03-06 17:15:06,491: 	 Found CRAB cache file /afs/cern.ch/user/k/knash/.crab3
DEBUG 2019-03-06 17:15:06,523: 	 Checking credentials
DEBUG 2019-03-06 17:15:06,525: 	 Found proxy file /tmp/x509up_u16529
DEBUG 2019-03-06 17:15:06,525: 	 Getting proxy life time left
DEBUG 2019-03-06 17:15:09,408: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u16529 -timeleft
 output : 25755

 error: 
 retcode : 0
DEBUG 2019-03-06 17:15:11,456: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u16529 -actimeleft
 output : 25753

 error: 
 retcode : 0
DEBUG 2019-03-06 17:15:11,456: 	 Proxy lifetime 25755 secs is different from voms extension lifetime 25753 secs for proxy: /tmp/x509up_u16529
DEBUG 2019-03-06 17:15:11,456: 	 Proxy valid for 07:09:13 hours
INFO 2019-03-06 17:15:11,458: 	 Will use CRAB configuration file crab3_TEMPJetHT.py
DEBUG 2019-03-06 17:15:11,458: 	 Loading CRAB configuration file.
DEBUG 2019-03-06 17:15:11,508: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-03-06 17:15:11,508: 	 Working area '/afs/cern.ch/work/k/knash/NanoAODskim/CMSSW_10_2_9/src/PhysicsTools/NanoHRT/test/crab_projects/crab_JetHTNanoSlimNtuples_v3' already exists 
Please change the requestName in the config file
ERROR 2019-03-06 17:15:11,509: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 313, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/k/knash/NanoAODskim/CMSSW_10_2_9/src/PhysicsTools/NanoHRT/test/crab_projects/crab_JetHTNanoSlimNtuples_v3' already exists 
Please change the requestName in the config file
DEBUG 2019-03-06 17:26:07,957: 	 Executing command: 'submit'
DEBUG 2019-03-06 17:26:07,958: 	 Found CRAB cache file /afs/cern.ch/user/k/knash/.crab3
DEBUG 2019-03-06 17:26:07,980: 	 Checking credentials
DEBUG 2019-03-06 17:26:07,982: 	 Found proxy file /tmp/x509up_u16529
DEBUG 2019-03-06 17:26:07,982: 	 Getting proxy life time left
DEBUG 2019-03-06 17:26:10,124: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u16529 -timeleft
 output : 25094

 error: 
 retcode : 0
DEBUG 2019-03-06 17:26:12,274: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u16529 -actimeleft
 output : 25092

 error: 
 retcode : 0
DEBUG 2019-03-06 17:26:12,276: 	 Proxy lifetime 25094 secs is different from voms extension lifetime 25092 secs for proxy: /tmp/x509up_u16529
DEBUG 2019-03-06 17:26:12,276: 	 Proxy valid for 06:58:12 hours
INFO 2019-03-06 17:26:12,276: 	 Will use CRAB configuration file crab3_TEMPJetHT.py
DEBUG 2019-03-06 17:26:12,276: 	 Loading CRAB configuration file.
DEBUG 2019-03-06 17:26:12,352: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-03-06 17:26:12,353: 	 Working area '/afs/cern.ch/work/k/knash/NanoAODskim/CMSSW_10_2_9/src/PhysicsTools/NanoHRT/test/crab_projects/crab_JetHTNanoSlimNtuples_v3' already exists 
Please change the requestName in the config file
ERROR 2019-03-06 17:26:12,353: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 313, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/k/knash/NanoAODskim/CMSSW_10_2_9/src/PhysicsTools/NanoHRT/test/crab_projects/crab_JetHTNanoSlimNtuples_v3' already exists 
Please change the requestName in the config file
DEBUG 2019-03-06 17:26:13,966: 	 Executing command: 'submit'
DEBUG 2019-03-06 17:26:13,967: 	 Found CRAB cache file /afs/cern.ch/user/k/knash/.crab3
DEBUG 2019-03-06 17:26:13,978: 	 Checking credentials
DEBUG 2019-03-06 17:26:13,979: 	 Found proxy file /tmp/x509up_u16529
DEBUG 2019-03-06 17:26:13,979: 	 Getting proxy life time left
DEBUG 2019-03-06 17:26:15,824: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u16529 -timeleft
 output : 25089

 error: 
 retcode : 0
DEBUG 2019-03-06 17:26:17,784: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u16529 -actimeleft
 output : 25087

 error: 
 retcode : 0
DEBUG 2019-03-06 17:26:17,785: 	 Proxy lifetime 25089 secs is different from voms extension lifetime 25087 secs for proxy: /tmp/x509up_u16529
DEBUG 2019-03-06 17:26:17,785: 	 Proxy valid for 06:58:07 hours
INFO 2019-03-06 17:26:17,785: 	 Will use CRAB configuration file crab3_TEMPJetHT.py
DEBUG 2019-03-06 17:26:17,785: 	 Loading CRAB configuration file.
DEBUG 2019-03-06 17:26:17,896: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-03-06 17:26:17,897: 	 Working area '/afs/cern.ch/work/k/knash/NanoAODskim/CMSSW_10_2_9/src/PhysicsTools/NanoHRT/test/crab_projects/crab_JetHTNanoSlimNtuples_v3' already exists 
Please change the requestName in the config file
ERROR 2019-03-06 17:26:17,897: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 313, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/k/knash/NanoAODskim/CMSSW_10_2_9/src/PhysicsTools/NanoHRT/test/crab_projects/crab_JetHTNanoSlimNtuples_v3' already exists 
Please change the requestName in the config file
DEBUG 2019-03-06 17:26:19,799: 	 Executing command: 'submit'
DEBUG 2019-03-06 17:26:19,804: 	 Found CRAB cache file /afs/cern.ch/user/k/knash/.crab3
DEBUG 2019-03-06 17:26:19,816: 	 Checking credentials
DEBUG 2019-03-06 17:26:19,817: 	 Found proxy file /tmp/x509up_u16529
DEBUG 2019-03-06 17:26:19,817: 	 Getting proxy life time left
DEBUG 2019-03-06 17:26:21,360: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u16529 -timeleft
 output : 25083

 error: 
 retcode : 0
DEBUG 2019-03-06 17:26:23,249: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u16529 -actimeleft
 output : 25081

 error: 
 retcode : 0
DEBUG 2019-03-06 17:26:23,249: 	 Proxy lifetime 25083 secs is different from voms extension lifetime 25081 secs for proxy: /tmp/x509up_u16529
DEBUG 2019-03-06 17:26:23,249: 	 Proxy valid for 06:58:01 hours
INFO 2019-03-06 17:26:23,250: 	 Will use CRAB configuration file crab3_TEMPJetHT.py
DEBUG 2019-03-06 17:26:23,251: 	 Loading CRAB configuration file.
DEBUG 2019-03-06 17:26:23,452: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-03-06 17:26:23,452: 	 Working area '/afs/cern.ch/work/k/knash/NanoAODskim/CMSSW_10_2_9/src/PhysicsTools/NanoHRT/test/crab_projects/crab_JetHTNanoSlimNtuples_v3' already exists 
Please change the requestName in the config file
ERROR 2019-03-06 17:26:23,453: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 313, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/k/knash/NanoAODskim/CMSSW_10_2_9/src/PhysicsTools/NanoHRT/test/crab_projects/crab_JetHTNanoSlimNtuples_v3' already exists 
Please change the requestName in the config file
DEBUG 2019-03-06 17:26:24,146: 	 Executing command: 'submit'
DEBUG 2019-03-06 17:26:24,146: 	 Found CRAB cache file /afs/cern.ch/user/k/knash/.crab3
DEBUG 2019-03-06 17:26:24,172: 	 Checking credentials
DEBUG 2019-03-06 17:26:24,174: 	 Found proxy file /tmp/x509up_u16529
DEBUG 2019-03-06 17:26:24,174: 	 Getting proxy life time left
DEBUG 2019-03-06 17:26:26,241: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u16529 -timeleft
 output : 25078

 error: 
 retcode : 0
DEBUG 2019-03-06 17:26:28,406: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u16529 -actimeleft
 output : 25076

 error: 
 retcode : 0
DEBUG 2019-03-06 17:26:28,407: 	 Proxy lifetime 25078 secs is different from voms extension lifetime 25076 secs for proxy: /tmp/x509up_u16529
DEBUG 2019-03-06 17:26:28,407: 	 Proxy valid for 06:57:56 hours
INFO 2019-03-06 17:26:28,407: 	 Will use CRAB configuration file crab3_TEMPJetHT.py
DEBUG 2019-03-06 17:26:28,408: 	 Loading CRAB configuration file.
DEBUG 2019-03-06 17:26:28,501: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-03-06 17:26:28,502: 	 Working area '/afs/cern.ch/work/k/knash/NanoAODskim/CMSSW_10_2_9/src/PhysicsTools/NanoHRT/test/crab_projects/crab_JetHTNanoSlimNtuples_v3' already exists 
Please change the requestName in the config file
ERROR 2019-03-06 17:26:28,502: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 313, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/k/knash/NanoAODskim/CMSSW_10_2_9/src/PhysicsTools/NanoHRT/test/crab_projects/crab_JetHTNanoSlimNtuples_v3' already exists 
Please change the requestName in the config file
DEBUG 2019-03-06 17:26:29,512: 	 Executing command: 'submit'
DEBUG 2019-03-06 17:26:29,512: 	 Found CRAB cache file /afs/cern.ch/user/k/knash/.crab3
DEBUG 2019-03-06 17:26:29,525: 	 Checking credentials
DEBUG 2019-03-06 17:26:29,528: 	 Found proxy file /tmp/x509up_u16529
DEBUG 2019-03-06 17:26:29,528: 	 Getting proxy life time left
DEBUG 2019-03-06 17:26:31,783: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u16529 -timeleft
 output : 25073

 error: 
 retcode : 0
DEBUG 2019-03-06 17:26:33,729: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u16529 -actimeleft
 output : 25071

 error: 
 retcode : 0
DEBUG 2019-03-06 17:26:33,730: 	 Proxy lifetime 25073 secs is different from voms extension lifetime 25071 secs for proxy: /tmp/x509up_u16529
DEBUG 2019-03-06 17:26:33,730: 	 Proxy valid for 06:57:51 hours
INFO 2019-03-06 17:26:33,730: 	 Will use CRAB configuration file crab3_TEMPJetHT.py
DEBUG 2019-03-06 17:26:33,730: 	 Loading CRAB configuration file.
DEBUG 2019-03-06 17:26:33,802: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-03-06 17:26:33,803: 	 Working area '/afs/cern.ch/work/k/knash/NanoAODskim/CMSSW_10_2_9/src/PhysicsTools/NanoHRT/test/crab_projects/crab_JetHTNanoSlimNtuples_v3' already exists 
Please change the requestName in the config file
ERROR 2019-03-06 17:26:33,803: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 313, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1902.patch1/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/k/knash/NanoAODskim/CMSSW_10_2_9/src/PhysicsTools/NanoHRT/test/crab_projects/crab_JetHTNanoSlimNtuples_v3' already exists 
Please change the requestName in the config file
DEBUG 2019-03-06 19:00:12,156: 	 Executing command: 'submit'
DEBUG 2019-03-06 19:00:12,157: 	 Found CRAB cache file /afs/cern.ch/user/k/knash/.crab3
DEBUG 2019-03-06 19:00:12,173: 	 Checking credentials
DEBUG 2019-03-06 19:00:12,175: 	 Found proxy file /tmp/x509up_u16529
DEBUG 2019-03-06 19:00:12,175: 	 Getting proxy life time left
ERROR 2019-03-06 19:00:13,821: 	 Keyboard Interrupted
DEBUG 2019-03-11 14:45:04,963: 	 Executing command: 'submit'
DEBUG 2019-03-11 14:45:04,963: 	 Found CRAB cache file /afs/cern.ch/user/k/knash/.crab3
DEBUG 2019-03-11 14:45:04,978: 	 Checking credentials
DEBUG 2019-03-11 14:45:04,979: 	 Found proxy file /tmp/x509up_u16529
DEBUG 2019-03-11 14:45:04,979: 	 Getting proxy life time left
ERROR 2019-03-11 14:45:05,708: 	 Keyboard Interrupted
DEBUG 2019-03-11 14:51:23,289: 	 Executing command: 'submit'
DEBUG 2019-03-11 14:51:23,289: 	 Found CRAB cache file /afs/cern.ch/user/k/knash/.crab3
DEBUG 2019-03-11 14:51:23,353: 	 Checking credentials
DEBUG 2019-03-11 14:51:23,354: 	 Found proxy file /tmp/x509up_u16529
DEBUG 2019-03-11 14:51:23,354: 	 Getting proxy life time left
DEBUG 2019-03-11 14:51:25,071: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u16529 -timeleft
 output : 41115

 error: 
 retcode : 0
DEBUG 2019-03-11 14:51:26,583: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u16529 -actimeleft
 output : 41114

 error: 
 retcode : 0
DEBUG 2019-03-11 14:51:26,584: 	 Proxy lifetime 41115 secs is different from voms extension lifetime 41114 secs for proxy: /tmp/x509up_u16529
DEBUG 2019-03-11 14:51:26,584: 	 Proxy valid for 11:25:14 hours
INFO 2019-03-11 14:51:26,584: 	 Will use CRAB configuration file crab3_TEMPJetHT.py
DEBUG 2019-03-11 14:51:26,585: 	 Loading CRAB configuration file.
DEBUG 2019-03-11 14:51:26,587: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-03-11 14:51:26,590: 	 Working area '/afs/cern.ch/work/k/knash/NanoAODskim/CMSSW_10_2_9/src/PhysicsTools/NanoHRT/test/crab_projects/crab_JetHTRun2017B-31Mar2018-v1NanoSlimNtuples_v6' already exists 
Please change the requestName in the config file
ERROR 2019-03-11 14:51:26,591: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/k/knash/NanoAODskim/CMSSW_10_2_9/src/PhysicsTools/NanoHRT/test/crab_projects/crab_JetHTRun2017B-31Mar2018-v1NanoSlimNtuples_v6' already exists 
Please change the requestName in the config file
